<?php

namespace App\Filament\Resources\UserAuthLogResource;

use App\Models\UserAuthLog;
use BackedEnum;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\TextInput;
use Filament\Infolists\Components\TextEntry;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use UnitEnum;

class UserAuthLogResource extends Resource
{
    protected static ?string $model = UserAuthLog::class;

    protected static ?string $slug = 'user-auth-logs';

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    /**
     * @return string|null
     */
    public static function getPluralLabel(): ?string
    {
        return __('login_history');
    }

    /**
     * @return string|null
     */
    public static function getNavigationLabel(): string
    {
        return __('login_history');
    }

    public static function getLabel(): ?string
    {
        return __('login_history');
    }

    public static function getNavigationGroup(): string|UnitEnum|null
    {
        return __('navigation.analytics');
    }

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([

            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('user.name')
                    ->label(__('user'))
                    ->searchable()
                    ->sortable(),

                TextColumn::make('login_at')
                    ->label(__('login_time'))
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('logout_at')
                    ->label(__('logout_time'))
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('ip_address')
                    ->label(__('ip_address'))
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
                TextColumn::make('user_agent')
                    ->label(__('user_agent'))
                    ->limit(50)
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
            ])
            ->filters([
                SelectFilter::make('user_id')
                    ->label(__('user'))
                    ->relationship('user', 'name'),
            ], FiltersLayout::AboveContent);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListUserAuthLogs::route('/'),
//            'create' => Pages\CreateUserAuthLog::route('/create'),
//            'edit' => Pages\EditUserAuthLog::route('/{record}/edit'),
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->with(['user']); // TODO: Change the autogenerated stub
    }
}
